### ISSUE TITLE
Combine

### ISSUE THREAD

**Issue by ITPhoneHome** [craftwar/suspend#1]
Hello, great script. Not really an issue. Is there anyway to "Combine" like to toggle suspend and resume? If a process is suspended, re-clicking the same bat/cmd would do the opposite, resume.
If the same process was running clicking the same script would suspend.

Thanks!

**Comment by craftwar** [comment]
I don't have much interest to support niche feature.

If you want to implement it, this may help you.
https://stackoverflow.com/questions/4510534/how-to-find-if-the-process-is-suspended-or-not

**Comment by ITPhoneHome** [comment]
Thank you!
